version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-api:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    container_name: auth-api
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"

  data-api:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    container_name: data-api
    env_file: .env
    ports:
      - "8081:8081"

volumes:
  postgres_data:
